AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Service Stack


Mappings:

  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  FunctionName:
    GetPreSignedUrlFunction:
      test: test-get-presigned-url-image
      stage: stage-get-presigned-url-image
      prod: prod-get-presigned-url-image
    GetPreSignedUrlFunctionTargetGroup:
      test: test-get-presigned-url-image-tg
      stage: stage-get-presigned-url-image-tg
      prod: prod-get-presigned-url-image-tg

    InternalHandleUploadFunction:
      test: test-internal-handle-upload-image
      stage: stage-internal-handle-upload-image
      prod: prod-internal-handle-upload-image

    GetOwnPhotosFunction:
      test: test-get-own-photos-image
      stage: stage-get-own-photos-image
      prod: prod-get-own-photos-image
    GetOwnPhotosFunctionTargetGroup:
      test: test-get-own-photos-image-tg
      stage: stage-get-own-photos-image-tg
      prod: prod-get-own-photos-image-tg

    DeletePhotoFunction:
      test: test-delete-photo-image
      stage: stage-delete-photo-image
      prod: prod-delete-photo-image
    DeletePhotoFunctionTargetGroup:
      test: test-delete-photo-image-tg
      stage: stage-delete-photo-image-tg
      prod: prod-delete-photo-image-tg

    InternalHandleAsyncTaskFunction:
      test: test-internal-handle-async-task-image
      stage: stage-internal-handle-async-task-image
      prod: prod-internal-handle-async-task-image
    InternalPresignFunction:
      test: test-internal-presign-url-image
      stage: stage-internal-presign-url-image
      prod: prod-internal-presign-url-image
    InternalGetImagesFunction:
      test: test-internal-get-images-image
      stage: stage-internal-get-images-image
      prod: prod-internal-get-images-image
    InternalCleanDbImageFunction:
      test: test-internal-clean-db-image
      stage: stage-internal-clean-db-image
      prod: prod-internal-clean-db-image


Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name
  BaseOriginPhotoBucketName:
    Type: String
    Default: ringoid-origin-photo
  BasePublicPhotoBucketName:
    Type: String
    Default: ringoid-public-photo


Globals:
    Function:
        Timeout: 300
        MemorySize: 512
        Runtime: go1.x
        Environment:
          Variables:
            ENV: !Ref Env
            PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
            DELIVERY_STREAM:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, DeliveryStreamExportName] ]
            INTERNAL_AUTH_FUNCTION_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalGetUserIdFunctionExport] ]
            PRESIGN_FUNCTION_NAME: !FindInMap [FunctionName, InternalPresignFunction, !Ref Env]
            ORIGIN_PHOTO_BUCKET_NAME: !Join [ "-", [ !Ref Env, !Ref BaseOriginPhotoBucketName] ]
            PHOTO_USER_MAPPING_TABLE: !Ref PhotoUserMappingTable
            USER_PHOTO_TABLE: !Ref UserPhotoTable
            PUBLIC_PHOTO_BUCKET_NAME: !Join [ "-", [ !Ref Env, !Ref BasePublicPhotoBucketName] ]
            ASYNC_TASK_SQS_QUEUE: !Ref AsyncTaskSqsQueue
            COMMON_STREAM:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, CommonEventStreamExportName] ]
            INTERNAL_STREAM_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalEventStreamExportName] ]
        Tags:
          Company: Ringoid
          Service: image
          Environment: !Ref Env

Resources:

  InternalCleanDbImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, InternalCleanDbImageFunction, !Ref Env]
      Handler: clean
      CodeUri: ../clean.zip
      Description: Clean DB image function
      Policies:
        - AWSLambdaFullAccess
        - AmazonDynamoDBFullAccess

  GetPreSignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, GetPreSignedUrlFunction, !Ref Env]
      Handler: get_presigned_url
      CodeUri: ../getpresigned-image.zip
      Description: Get Pre-Signed url image function
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - AmazonKinesisFirehoseFullAccess

  GetPreSignedUrlTargetGroup:
    Type: Custom::CreateTargetGroup
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, CustomResourceFunctionExport] ]
      CustomName: !FindInMap [FunctionName, GetPreSignedUrlFunctionTargetGroup, !Ref Env]
      CustomTargetsId: !GetAtt GetPreSignedUrlFunction.Arn
      TargetLambdaFunctionName: !Ref GetPreSignedUrlFunction

  GetPreSignedUrlListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !GetAtt GetPreSignedUrlTargetGroup.TargetGroupArn
      Conditions:
        - Field: path-pattern
          Values:
            - "/image/get_presigned"
      ListenerArn:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, ListenerArnExport] ]
      Priority: 201


  OriginPhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ !Ref Env, !Ref BaseOriginPhotoBucketName] ]
      NotificationConfiguration:
        LambdaConfigurations:
          -
            Function: !GetAtt InternalHandleUploadFunction.Arn
            Event: "s3:ObjectCreated:*"

  InternalHandleUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, InternalHandleUploadFunction, !Ref Env]
      Handler: internal_handle_upload
      CodeUri: ../internal_handle_upload.zip
      Description: Handle uploaded images
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonS3FullAccess
        - AmazonKinesisFullAccess

  PermissionForEventsToInvokeInternalHandleUploadFunction:
    Type: AWS::Lambda::Permission
    DependsOn: OriginPhotoBucket
    Properties:
      FunctionName: !Ref InternalHandleUploadFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - OriginPhotoBucket
          - Arn

  PublicPhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Join [ "-", [ !Ref Env, !Ref BasePublicPhotoBucketName] ]

  GetOwnPhotosFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, GetOwnPhotosFunction, !Ref Env]
      Handler: get_own_photos
      CodeUri: ../get_own_photos.zip
      Description: Get all user's photos
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - AmazonKinesisFirehoseFullAccess

  GetOwnPhotosTargetGroup:
    Type: Custom::CreateTargetGroup
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, CustomResourceFunctionExport] ]
      CustomName: !FindInMap [FunctionName, GetOwnPhotosFunctionTargetGroup, !Ref Env]
      CustomTargetsId: !GetAtt GetOwnPhotosFunction.Arn
      TargetLambdaFunctionName: !Ref GetOwnPhotosFunction

  GetOwnPhotosListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !GetAtt GetOwnPhotosTargetGroup.TargetGroupArn
      Conditions:
        - Field: path-pattern
          Values:
            - "/image/get_own_photos"
      ListenerArn:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, ListenerArnExport] ]
      Priority: 202

  DeletePhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, DeletePhotoFunction, !Ref Env]
      Handler: delete_photo
      CodeUri: ../delete_photo.zip
      Description: Delete user's photo
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonSQSFullAccess

  DeletePhotoTargetGroup:
    Type: Custom::CreateTargetGroup
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, CustomResourceFunctionExport] ]
      CustomName: !FindInMap [FunctionName, DeletePhotoFunctionTargetGroup, !Ref Env]
      CustomTargetsId: !GetAtt DeletePhotoFunction.Arn
      TargetLambdaFunctionName: !Ref DeletePhotoFunction

  DeletePhotoListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !GetAtt DeletePhotoTargetGroup.TargetGroupArn
      Conditions:
        - Field: path-pattern
          Values:
            - "/image/delete_photo"
      ListenerArn:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, ListenerArnExport] ]
      Priority: 203

  AsyncTaskSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref Env, image, async-task-queue] ]
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - AsyncTaskDeadMessageSqsQueue
            - Arn
        maxReceiveCount: 3

  AsyncTaskDeadMessageSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref Env, image, async-task-dead-messages-queue] ]
      VisibilityTimeout: 300

  InternalHandleAsyncTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, InternalHandleAsyncTaskFunction, !Ref Env]
      Handler: internal_handle_task
      CodeUri: ../internal_handle_task.zip
      Description: Handle async task from the queue
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
        - AmazonS3FullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonKinesisFullAccess
      Events:
        StartEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
                - AsyncTaskSqsQueue
                - Arn
            BatchSize: 10

  KinesisConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref Env, internal-stream-consumer-image] ]
      Handler: handle_stream
      CodeUri: ../handle_stream.zip
      Description: Consumer for Kinesis stream
      Policies:
        - AmazonKinesisFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
        - AmazonKinesisFirehoseFullAccess
      Events:
        CommonEventStreamEvent:
          Type: Kinesis
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalEventStreamExport] ]
            StartingPosition: TRIM_HORIZON
            BatchSize: 1

  InternalGetImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, InternalGetImagesFunction, !Ref Env]
      Handler: get_images
      CodeUri: ../get_images.zip
      Description: Internal Get Images function
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonKinesisFirehoseFullAccess

  PhotoUserMappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
          TableName: !Join [ "-", [ !Ref Env, Image, PhotoUserMappingTable] ]
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            -
              AttributeName: photo_id
              AttributeType: S
          KeySchema:
            -
              AttributeName: photo_id
              KeyType: HASH
          Tags:
            - Key: Company
              Value: Ringoid
            - Key: Service
              Value: image
            - Key: Environment
              Value: !Ref Env

  UserPhotoTable:
    Type: AWS::DynamoDB::Table
    Properties:
          TableName: !Join [ "-", [ !Ref Env, Image, UserPhotoTable] ]
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: true
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            -
              AttributeName: user_id
              AttributeType: S
            -
              AttributeName: photo_id
              AttributeType: S

          KeySchema:
            -
              AttributeName: user_id
              KeyType: HASH
            -
              AttributeName: photo_id
              KeyType: RANGE
          Tags:
            - Key: Company
              Value: Ringoid
            - Key: Service
              Value: image
            - Key: Environment
              Value: !Ref Env

Outputs:
  InternalGetImagesFunctionExport:
    Value: !FindInMap [FunctionName, InternalGetImagesFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, InternalGetImagesFunctionExport] ]
  InternalCleanDbImageFunctionExport:
    Value: !FindInMap [FunctionName, InternalCleanDbImageFunction, !Ref Env]
    Export:
      Name: !Join [ "-", [ !Ref Env, InternalCleanDbImageFunctionExport] ]
