AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Service Stack


Mappings:

  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  FunctionName:
    InternalHandleUploadFunction:
      test: test-internal-handle-upload-image
      stage: stage-internal-handle-upload-image
      prod: prod-internal-handle-upload-image

Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name
  BaseOriginPhotoBucketName:
    Type: String
    Default: ringoid-origin-photo

Globals:
    Function:
        Timeout: 300
        MemorySize: 512
        Runtime: go1.x
        Tags:
          Company: Ringoid
          Service: image
          Environment: !Ref Env

Resources:

  OriginPhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ !Ref Env, !Ref BaseOriginPhotoBucketName] ]

  InternalHandleUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, InternalHandleUploadFunction, !Ref Env]
      Handler: internal_handle_upload
      CodeUri: ../internal_handle_upload.zip
      Description: Handle uploaded images
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonS3FullAccess
        - AmazonKinesisFullAccess

  PermissionForEventsToInvokeInternalHandleUploadFunction:
    Type: AWS::Lambda::Permission
    DependsOn: OriginPhotoBucket
    Properties:
      FunctionName: !Ref InternalHandleUploadFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - OriginPhotoBucket
          - Arn
