AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Service Stack

Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name
  BaseOriginPhotoBucketName:
    Type: String
    Default: ringoid-origin-photo

Resources:

  OriginPhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ !Ref Env, !Ref BaseOriginPhotoBucketName] ]
